<?php

namespace App\Http\Controllers;

use App\Enums\OrderStatus;
use App\Models\Order;
use App\Models\DataPembayaran;
use App\Models\Expense; // Pastikan path model ini benar
use App\Models\ExpenseOps;
use App\Models\PaymentMethod;
use Barryvdh\DomPDF\Facade\Pdf;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Str; // Import PDF Facade
use Illuminate\View\View;

class ReportController extends Controller
{
    public function generateDataPembayaranHtmlReport(Request $request): View
    {
        $selectedMonth = $request->input('month');
        $selectedYear = $request->input('year');
        $selectedStatus = $request->input('status'); // Ambil dari request

        // Data untuk dropdown filter
        $months = [];
        for ($m = 1; $m <= 12; $m++) {
            $months[str_pad($m, 2, '0', STR_PAD_LEFT)] = Carbon::create()->month($m)->locale('id')->isoFormat('MMMM');
        }

        // Ambil tahun unik dari data pembayaran yang ada, atau default ke rentang beberapa tahun
        $availableYearsDb = DataPembayaran::selectRaw('DISTINCT YEAR(tgl_bayar) as year')
            ->whereNotNull('tgl_bayar')
            ->orderBy('year', 'desc')
            ->pluck('year')
            ->filter() // Menghilangkan nilai null jika ada
            ->toArray();

        $currentYear = (int) date('Y');
        $defaultYears = range($currentYear, $currentYear - 5);
        $years = ! empty($availableYearsDb) ? $availableYearsDb : $defaultYears;
        if (! empty($availableYearsDb) && $selectedYear && ! in_array($selectedYear, $years)) {
            // Jika tahun yang dipilih tidak ada di daftar tahun dari DB (misal dari input manual URL), tambahkan
            array_push($years, (int) $selectedYear);
            sort($years, SORT_NUMERIC);
            $years = array_reverse($years);
        }

        $orderStatuses = OrderStatus::cases();

        $query = DataPembayaran::query()->with(['order', 'paymentMethod']); // Load order, status is an attribute

        if ($selectedMonth && $selectedYear) {
            $query->whereYear('tgl_bayar', $selectedYear)
                ->whereMonth('tgl_bayar', $selectedMonth);
        } elseif ($selectedYear) {
            $query->whereYear('tgl_bayar', $selectedYear);
        }

        // Tambahkan filter status
        if ($selectedStatus) {
            $query->whereHas('order', function ($q) use ($selectedStatus) {
                $q->where('status', $selectedStatus); // Asumsi kolom status di tabel order
            });
        }

        $dataPembayarans = $query
            ->join('orders', 'data_pembayarans.order_id', '=', 'orders.id')
            ->select('data_pembayarans.*')
            ->with(['order.product']) // Eager load single product relation
            ->orderBy('orders.name', 'asc')
            ->orderBy('data_pembayarans.tgl_bayar', 'asc')
            ->get();

        return view('reports.pembayaran_html', compact(
            'dataPembayarans',
            'months',
            'years',
            'selectedMonth',
            'selectedYear',
            'orderStatuses',
            'selectedStatus'
        ));
    }

    public function generateDataPembayaranPdfReport(Request $request)
    {
        ini_set('memory_limit', '512M');
        ini_set('max_execution_time', '300');

        $selectedMonth = $request->input('month');
        $selectedYear = $request->input('year');
        $selectedStatus = $request->input('status');

        $query = DataPembayaran::query()->with(['order', 'paymentMethod']);

        // Jika filter tanggal aktif, sesuaikan nama kolom karena query sudah di-join nanti
        // Tapi query builder whereYear/Month otomatis nambahin table name kalau pakai model,
        // cuma amannya kita spesifikkan table name 'data_pembayarans' untuk menghindari ambiguitas dengan 'orders'

        if ($selectedMonth && $selectedYear) {
            $query->whereYear('data_pembayarans.tgl_bayar', $selectedYear)
                ->whereMonth('data_pembayarans.tgl_bayar', $selectedMonth);
        } elseif ($selectedYear) {
            $query->whereYear('data_pembayarans.tgl_bayar', $selectedYear);
        }

        if ($selectedStatus) {
            $query->whereHas('order', function ($q) use ($selectedStatus) {
                $q->where('status', $selectedStatus);
            });
        }

        // Use withoutGlobalScopes() to ensure we get all orders regardless of user assignment
        // This is important for reports that might be generated by admins or finance users
        // who need to see all data, bypassing the user_id filter in Order::getEloquentQuery
        $dataPembayarans = $query
            ->leftJoin('orders', 'data_pembayarans.order_id', '=', 'orders.id')
            ->select('data_pembayarans.*') // Ambil hanya kolom dari data_pembayarans agar tidak tertimpa kolom orders (misal id)
            ->with(['order' => function ($query) {
                $query->withoutGlobalScopes()->with('product');
            }]) 
            ->orderBy('orders.name', 'asc')
            ->orderBy('data_pembayarans.tgl_bayar', 'asc')
            ->get();

        // Debugging: Jika data kosong, return text untuk memastikan
        if ($dataPembayarans->isEmpty()) {
            return response('Data Pembayaran Kosong (Count: 0). Cek apakah ada data di database atau filter tanggal.', 200);
        }

        $pdf = Pdf::loadView('reports.pembayaran_pdf', compact('dataPembayarans'))
            ->setPaper('a4', 'portrait');

        return $pdf->stream('laporan_pembayaran_' . date('Y-m-d_H-i-s') . '.pdf');
    }

    public function generateExpenseOpsHtmlReport(Request $request): View
    {
        $query = ExpenseOps::query(); // Using fully qualified name to avoid ambiguity

        $selectedMonth = $request->input('month');
        $selectedYear = $request->input('year');
        $searchName = $request->input('search_name');
        $searchNote = $request->input('search_note');

        if ($selectedYear) {
            $query->whereYear('date_expense', $selectedYear);
            if ($selectedMonth) {
                $query->whereMonth('date_expense', $selectedMonth);
            }
        }

        if ($searchName) {
            $query->where('name', 'like', '%'.$searchName.'%');
        }

        if ($searchNote) {
            // Jika kolom catatan Anda adalah 'note'
            // Jika nama kolomnya berbeda, sesuaikan 'note' di bawah ini
            $query->where('note', 'like', '%'.$searchNote.'%');
        }

        $expenseOps = $query->orderBy('date_expense', 'desc')->get();

        // Data untuk dropdown filter
        $months = [];
        for ($m = 1; $m <= 12; $m++) {
            $months[str_pad($m, 2, '0', STR_PAD_LEFT)] = Carbon::create()->month($m)->locale('id')->isoFormat('MMMM');
        }

        // Ambil tahun unik dari data pengeluaran operasional yang ada
        $availableYearsDb = ExpenseOps::selectRaw('DISTINCT YEAR(date_expense) as year')
            ->whereNotNull('date_expense')
            ->orderBy('year', 'desc')
            ->pluck('year')
            ->filter()
            ->toArray();

        $currentYear = (int) date('Y');
        $defaultYears = range($currentYear, $currentYear - 5);
        $years = ! empty($availableYearsDb) ? $availableYearsDb : $defaultYears;

        // Pastikan tahun yang dipilih ada dalam daftar tahun yang tersedia
        if (! empty($availableYearsDb) && $selectedYear && ! in_array($selectedYear, $years)) {
            array_push($years, (int) $selectedYear);
            rsort($years); // Urutkan descending (terbaru ke terlama)
        }

        return view('reports.expense_ops_html', compact(
            'expenseOps',
            'months',
            'years',
            'selectedMonth',
            'selectedYear',
            'searchName',
            'searchNote'
        ));
    }

    public function generateExpenseOpsPdfReport(Request $request)
    {
        $query = ExpenseOps::query();

        $selectedMonth = $request->input('month');
        $selectedYear = $request->input('year');
        $searchName = $request->input('search_name');
        $searchNote = $request->input('search_note');

        if ($selectedYear) {
            $query->whereYear('date_expense', $selectedYear);
            if ($selectedMonth) {
                $query->whereMonth('date_expense', $selectedMonth);
            }
        }

        if ($searchName) {
            $query->where('name', 'like', '%'.$searchName.'%');
        }

        if ($searchNote) {
            $query->where('note', 'like', '%'.$searchNote.'%');
        }

        $expenseOps = $query->orderBy('date_expense', 'desc')->get();

        $months = [];
        for ($m = 1; $m <= 12; $m++) {
            $months[str_pad($m, 2, '0', STR_PAD_LEFT)] = Carbon::create()->month($m)->locale('id')->isoFormat('MMMM');
        }

        $availableYearsDb = ExpenseOps::selectRaw('DISTINCT YEAR(date_expense) as year')
            ->whereNotNull('date_expense')
            ->orderBy('year', 'desc')
            ->pluck('year')
            ->filter()
            ->toArray();
        $currentYear = (int) date('Y');
        $defaultYears = range($currentYear, $currentYear - 5);
        $years = ! empty($availableYearsDb) ? $availableYearsDb : $defaultYears;
        if (! empty($availableYearsDb) && $selectedYear && ! in_array($selectedYear, $years)) {
            array_push($years, (int) $selectedYear);
            rsort($years);
        }

        $data = compact('expenseOps', 'months', 'years', 'selectedMonth', 'selectedYear', 'searchName', 'searchNote');
        $pdf = Pdf::loadView('pdf.expense_ops_report_pdf', $data); // Menggunakan view PDF baru

        return $pdf->download('laporan-pengeluaran-operasional.pdf');
    }

    // Rute untuk laporan pengeluaran (expense wedding)
    public function generateExpenseHtmlReport(Request $request): View
    {
        $query = Expense::query(); // Menggunakan model Expense

        $selectedMonth = $request->input('month');
        $selectedYear = $request->input('year');
        $searchName = $request->input('search_name'); // Asumsi nama pengeluaran ada di kolom 'name'
        $searchNote = $request->input('search_note'); // Asumsi catatan ada di kolom 'note'
        $selectedOrderStatus = $request->input('order_status');
        $query = Expense::query()->with(['order', 'vendor']); // Pastikan relasi order di-load

        if ($selectedYear) {
            $query->whereYear('date_expense', $selectedYear);
            if ($selectedMonth) {
                $query->whereMonth('date_expense', $selectedMonth);
            }
        }

        if ($searchName) {
            $query->whereHas('order', function ($q) use ($searchName) {
                $q->where('name', 'like', '%'.$searchName.'%');
            });
        }

        if ($searchNote) {
            $query->where('note', 'like', '%'.$searchNote.'%');
        }

        if ($selectedOrderStatus) {
            $query->whereHas('order', function ($q) use ($selectedOrderStatus) {
                $q->where('status', $selectedOrderStatus);
            });
        }

        $expenses = $query->orderBy('date_expense', 'desc')->get();
        $expensesWedding = $query->get();
        $orderStatuses = OrderStatus::cases();

        // Data untuk dropdown filter
        $months = [];
        for ($m = 1; $m <= 12; $m++) {
            $months[str_pad($m, 2, '0', STR_PAD_LEFT)] = Carbon::create()->month($m)->locale('id')->isoFormat('MMMM');
        }

        $availableYearsDb = Expense::selectRaw('DISTINCT YEAR(date_expense) as year')
            ->whereNotNull('date_expense')
            ->orderBy('year', 'desc')
            ->pluck('year')
            ->filter()
            ->toArray();
        $currentYear = (int) date('Y');
        $defaultYears = range($currentYear, $currentYear - 5);
        $years = ! empty($availableYearsDb) ? $availableYearsDb : $defaultYears;
        if (! empty($availableYearsDb) && $selectedYear && ! in_array($selectedYear, $years)) {
            array_push($years, (int) $selectedYear);
            rsort($years);
        }

        return view('reports.expense_html', compact(
            'expenses',
            'months',
            'years',
            'selectedMonth',
            'selectedYear',
            'searchName',
            'searchNote',
            'orderStatuses',
            'selectedOrderStatus',
            'expensesWedding'
        ));
    }

    public function generateExpensePdfReport(Request $request)
    {
        $query = Expense::query(); // Menggunakan model Expense

        $selectedMonth = $request->input('month');
        $selectedYear = $request->input('year');
        $searchName = $request->input('search_name'); // Ini akan mencari nama dari relasi order
        $searchNote = $request->input('search_note');
        $selectedOrderStatus = $request->input('order_status'); // Ambil status order dari request

        if ($selectedYear) {
            $query->whereYear('date_expense', $selectedYear);
            if ($selectedMonth) {
                $query->whereMonth('date_expense', $selectedMonth);
            }
        }

        if ($searchName) {
            $query->whereHas('order', function ($q) use ($searchName) {
                $q->where('name', 'like', '%'.$searchName.'%');
            });
        }

        if ($searchNote) {
            $query->where('note', 'like', '%'.$searchNote.'%');
        }

        // Tambahkan filter status order jika ada
        if ($selectedOrderStatus) {
            $query->whereHas('order', function ($q) use ($selectedOrderStatus) {
                $q->where('status', $selectedOrderStatus);
            });
        }

        $expenses = $query->orderBy('date_expense', 'desc')->get();
        $orderStatuses = OrderStatus::cases(); // Ambil semua kasus status order

        $months = [];
        for ($m = 1; $m <= 12; $m++) {
            $months[str_pad($m, 2, '0', STR_PAD_LEFT)] = Carbon::create()->month($m)->locale('id')->isoFormat('MMMM');
        }

        $availableYearsDb = Expense::selectRaw('DISTINCT YEAR(date_expense) as year')
            ->whereNotNull('date_expense')
            ->orderBy('year', 'desc')
            ->pluck('year')
            ->filter()
            ->toArray();
        $currentYear = (int) date('Y');
        $defaultYears = range($currentYear, $currentYear - 5);
        $years = ! empty($availableYearsDb) ? $availableYearsDb : $defaultYears;
        if (! empty($availableYearsDb) && $selectedYear && ! in_array($selectedYear, $years)) {
            array_push($years, (int) $selectedYear);
            rsort($years);
        }

        $isPdf = true; // Flag untuk view PDF
        $data = compact(
            'expenses',
            'months',
            'years',
            'selectedMonth',
            'selectedYear',
            'searchName',
            'searchNote',
            'isPdf',
            'orderStatuses',         // Kirim ke view PDF
            'selectedOrderStatus'    // Kirim ke view PDF
        );

        $pdf = Pdf::loadView('pdf.expense_report_pdf', $data); // Menggunakan view PDF baru

        return $pdf->download('laporan-pengeluaran.pdf');
    }

    public function customerPayments(Request $request, string $status)
    {
        $query = DataPembayaran::whereHas('order', function ($query) use ($status) {
            $query->where('status', $status);
        })->with(['order.prospect', 'paymentMethod']) // Eager load relasi yang dibutuhkan
            ->orderBy('tgl_bayar', 'desc');

        // Ambil input filter
        $filterDateFrom = $request->input('date_from');
        $filterDateTo = $request->input('date_to');
        $filterPaymentMethodId = $request->input('payment_method_id');
        $filters = $request->only(['date_from', 'date_to', 'project_name', 'payment_method_id']);

        // Terapkan filter tanggal
        if ($filterDateFrom) {
            $query->whereDate('tgl_bayar', '>=', $filterDateFrom);
        }
        if ($filterDateTo) {
            $query->whereDate('tgl_bayar', '<=', $filterDateTo);
        }

        // Terapkan filter metode pembayaran
        if ($filterPaymentMethodId) {
            $query->where('payment_method_id', $filterPaymentMethodId);
        }

        // 4. Terapkan filter nama project (order name)
        if (! empty($filters['project_name'])) {
            $projectName = $filters['project_name'];
            $query->whereHas('order', function ($orderQuery) use ($projectName) {
                // Asumsi 'name' adalah kolom di tabel 'orders' yang ingin Anda filter
                $orderQuery->where('name', 'like', '%'.$projectName.'%');
                // Jika Anda juga ingin mencari di 'name_event' pada relasi 'prospect' dari 'order':
                $orderQuery->where('name', 'like', '%'.$projectName.'%')
                    ->orWhereHas('prospect', function ($prospectQuery) use ($projectName) {
                        $prospectQuery->where('name_event', 'like', '%'.$projectName.'%');
                    });
            });
        }

        $payments = $query->get();

        $totalPaymentsValue = $payments->sum('nominal');
        $pageTitle = 'Customer Payments: '.Str::ucfirst(str_replace('_', ' ', $status)); // Membuat judul lebih rapi
        $paymentMethods = PaymentMethod::orderBy('name')->get(); // Ambil metode pembayaran untuk filter

        return view('reports.customer_payments_overview', [
            'payments' => $payments,
            'status' => $status,
            'totalPaymentsValue' => $totalPaymentsValue,
            'pageTitle' => $pageTitle,
            'paymentMethods' => $paymentMethods, // Kirim ke view
            'filters' => $request->only(['date_from', 'date_to', 'payment_method_id']), // Kirim nilai filter saat ini
        ]);
    }

    public function streamNetCashFlowPdf(Request $request)
    {
        $status = $request->input('status', 'processing');
        $statusEnum = OrderStatus::tryFrom($status) ?? OrderStatus::Processing;

        $orders = Order::where('status', $statusEnum)
            ->with(['dataPembayaran', 'expenses', 'prospect', 'user', 'employee', 'items.product.parent'])
            ->get()
            ->map(function ($order) {
                $totalPayments = $order->dataPembayaran->sum('nominal');
                $totalExpenses = $order->expenses->sum('amount');
                $netCashFlow = $totalPayments - $totalExpenses;

                $order->total_payments_received = $totalPayments;
                $order->total_expenses_incurred = $totalExpenses;
                $order->net_cash_flow = $netCashFlow;

                return $order;
            })
            ->sortByDesc('net_cash_flow');

        $totalPaymentsAll = $orders->sum('total_payments_received');
        $totalExpensesAll = $orders->sum('total_expenses_incurred');
        $totalNetCashFlowAll = $orders->sum('net_cash_flow');

        $pageTitle = 'Laporan Arus Kas Bersih (Net Cash Flow) - Order Status: ' . Str::ucfirst($status);

        $pdf = Pdf::loadView('reports.net-cash-flow-pdf', [
            'orders' => $orders,
            'status' => $status,
            'totalPaymentsAll' => $totalPaymentsAll,
            'totalExpensesAll' => $totalExpensesAll,
            'totalNetCashFlowAll' => $totalNetCashFlowAll,
            'pageTitle' => $pageTitle,
        ]);

        return $pdf->stream('Laporan_Net_Cash_Flow_' . now()->format('Y-m-d_H-i') . '.pdf');
    }
}
